DefectDojo/sample-scan-files

goastscanner/README.md
goastscanner/goastscanner.json

Added GoAST Scanner sample files for reference. 
Note: 
the version tag for GoAST Scanner is missing yet. For more details please refer: https://github.com/GoASTScanner/gas

added GoASTScanner sample files

---

crashtest_security/README.md
crashtest_security/crashtest_security_v20190103.xml

Added a sample scan as requested in https://github.com/DefectDojo/django-DefectDojo/pull/837#issuecomment-451457926

add example report for crashtest security scanner

---

safety/README.md
safety/safety-scan.json

Relates to: [#848](https://github.com/DefectDojo/django-DefectDojo/pull/848)

Added safety sample scan data

---

dawnscanner/dawnscanner_v1.6.9.json

This is a sample json report generated by dawnscanner (using -j or --json option) against a ruby on rails code
This file supports this pull request to DefectDojo to import dawnscanner json reports: https://github.com/DefectDojo/django-DefectDojo/pull/995

dawnscanner v1.6.9 sample scan file

---

bundler-audit/bundler-audit_v0.6.1.txt

Sample scan file from [bundler-audit](https://github.com/rubysec/bundler-audit) tool, patch-level verification for bundler and Ruby projects

Bundler-Audit sample scan file

---

jfrogxray/many_vulns.json
jfrogxray/one_vuln.json

Relates to https://github.com/DefectDojo/django-DefectDojo/pull/1375
cc @Maffooch

Samples for Jfrog Xray

---

burp/burpvulns_v2_1_02.xml

BURP has a new major version (2.X) and this sample file contains 15 vulnerabilities that sucessfully import into Dojo 1.5.4-dev

Add new BURP sample report

---

qualys/Qualys_Sample_Report.xml

This is a sample Qualys Vulnerability Management report on the assets/ip range used for Qualys training.
Currently, there are 299 findings that are seamlessly imported into Dojo

Adding sample Qualys VM Report

---

sonarqube/sonar-report-v1.1.0_java-tomcat_Sonarcloud-v8.0.0.485.html

add sample with "key" to serve as "unique_id_from_tool" in the deduplication
linked to https://github.com/DefectDojo/django-DefectDojo/pull/1540

add sonarqube sample with key for unique_id_from_tool

---

dependency_track/README.md
dependency_track/dependency_track_findings_v3.4.0.json

Added an example OWASP Dependency Track Finding Export File to the scan file samples

Add example OWASP Dependency Track Finding Export File

---

fortify/README.md

Adding info on how to create Fortify XML files to import into Defect Dojo with all issues in XML file.

How to create Fortify XML files

---

outpost24/sample.xml

See https://github.com/DefectDojo/django-DefectDojo/pull/1750
@madchap

Add sample file for Outpost24

---

crashtest_security/crashtest_security_v20200308_data_extracted.json
crashtest_security/crashtest_security_v20200308_full.json

Add sample files for https://github.com/DefectDojo/django-DefectDojo/pull/1996

Add Crashtest Security JSON example files

---

choctaw_hog/choctaw_hog_scan.json

adding choctaw_hog sample

---

gitlab_sast/README.md
gitlab_sast/gl-sast-report-0-vuln.json
gitlab_sast/gl-sast-report-1-vuln.json
gitlab_sast/gl-sast-report-many-vuln.json

Main PR: https://github.com/DefectDojo/django-DefectDojo/pull/2195

Add GitLab SAST Report samples

---

eslint/README.md
eslint/eslint_v6.8.0.json

added eslint samples

---

ccvs/README.md
ccvs/many_vulns.json

This PR will add 1 example using CCVS Report

Add ccvs sample

---

huskyci/README.md
huskyci/huskyci_report_many_finding_one_tool.json
huskyci/huskyci_report_many_finding_two_tools.json
huskyci/huskyci_report_no_finding.json
huskyci/huskyci_report_one_finding_one_tool.json

This PR will add 1 example using huskyCI Report

Add huskyCI sample

---

aqua/aqua_v2_sample.json

https://github.com/DefectDojo/django-DefectDojo/issues/2389
https://github.com/DefectDojo/django-DefectDojo/pull/2711
@madchap

Add sample scan for Aqua v2

---

awssecurityhub/example.json

This is a sample of findings generated with two standards enabled:
- AWS Foundational Security Best Practices v1.0.0
- CIS AWS Foundations Benchmark v1.2.0
This will assist in developing a parser for DefectDojo/django-DefectDojo#2167.

Add example AWS Security Hub findings

---

acunetix/20200228_XML_http_www_itsecgames_com_.xml
acunetix/XML_http_example_co_id_.xml

Adding more Acunetix samples files based on @valentijnscholten comment

Adding Acunetix sample files

---

ort/README.md
ort/evaluated-model-reporter-output.json

Add sample for ORT (https://github.com/DefectDojo/django-DefectDojo/pull/3177#issuecomment-723496576)

add ORT sample

---

gitlab_dep_scan/README.md
gitlab_dep_scan/gl-dependency-scanning-report-0-vuln.json
gitlab_dep_scan/gl-dependency-scanning-report-1-vuln-missing-component.json
gitlab_dep_scan/gl-dependency-scanning-report-1-vuln.json
gitlab_dep_scan/gl-dependency-scanning-report-many-vuln.json

Add sample scan files for GitLab Dependency Scanning (see DefectDojo/django-DefectDojo#3534).

Add sample scan files for GitLab Dependency Scanning

---

veracode/veracode_dojo.json

Generated as `time srcclr scan --json ~/tmp/veracode_dojo.json --url https://github.com/DefectDojo/django-DefectDojo`
version used 3.7.45.

Veracode: json output from agent-based scan

---

veracode/veracode-docker-scan-dojodjango.json
veracode/veracode_dojo.json

Image scan:
Done with `time srcclr scan --json ~/tmp/veracode-docker-scan-dojodjango.json --image defectdojo/defectdojo-django:latest`
Running container scan:
`time srcclr scan --json ~/tmp/veracode-running-container-scan-dojodjango.json --container madchap_ddojo_uwsgi_1`
Agent version 3.7.45

Veracode - agent based docker scan

---

sslyze/one_target_many_vuln_new.json
sslyze/one_target_many_vuln_old.json
sslyze/one_target_one_vuln_new.json
sslyze/one_target_one_vuln_old.json
sslyze/one_target_zero_vuln_new.json
sslyze/one_target_zero_vuln_old.json
sslyze/two_targets_two_vuln_new.json
sslyze/two_targets_two_vuln_old.json

https://github.com/DefectDojo/django-DefectDojo/pull/5689
As requested in this PR

Added new scan files for sslyze

---

dependency_track/dependency_track_findings_v4.10.json

DependencyTrack file export has been changed a little over the time. Here is a sample export from the latest version v4.10.1

:tada: DependencyTrack file v4.10.1
